corona-warn-app/cwa-app-ios

- src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/Views/DynamicTableViewBulletPointCell.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinating.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsOnsetViewController.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionSymptomsViewController.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewController.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/ExposureSubmissionUITests.swift
- src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/__tests__/Mock Objects/MockExposureSubmissionCoordinator.swift
- src/xcode/ENA/ENA/Source/Scenes/OptionGroup/DatePickerOption/DatePickerDayView.swift
- src/xcode/ENA/ENA/Source/View Helpers/AccessibilityIdentifiers.swift
This pull request integrates the onset of symptoms screens into the exposure submission flow. 
JIRA: https://jira.itc.sap.com/browse/EXPOSUREAPP-2481
> Integrate onset of symptoms screens into the exposure submission flow

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Fixes https://jira.itc.sap.com/browse/EXPOSUREAPP-2595
> Update error message for invalid TANs

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Update Localizable.strings (2777)

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
New/updated texts for the following text keys:
"ExposureSubmissionSymptoms_Introduction"
"ExposureSubmissionSymptoms_Description"
"ExposureSubmissionWarnOthers_description"
"ExposureSubmissionWarnOthers_dataPrivacyTitle"
"ExposureSubmissionWarnOthers_dataPrivacyDescription"
Jira #2851
This PR contains the texts only (language: DE) for the translation to all other languages.
> New legal texts (Onset of Symptoms) – Text Strings

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
> Update privacy-policy.html (EXPOSURE-2832)

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
> Update privacy-policy.html (ESPOSUREAPP-2777)

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Text for ExposureDetection_Explanation_Text_Outdated
Solves Jira #2604
> Text Update; Jira 2604

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Update Localizable.strings #2931

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Update localizable strings for https://jira.itc.sap.com/browse/EXPOSUREAPP-3086
> Update localizable strings for test result screen

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Remove superfluous space. Jira: https://jira.itc.sap.com/browse/EXPOSUREAPP-2933
> Remove superfluous space #2933

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Update Localizable.strings 

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Adds new text and changes old one.
[3271](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3271)
> Change text and add new one.

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3384
> Update Localizable.strings #3384

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3251
> Update usage.html #3251

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Update Localizable.strings #3655

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1996
> Update Localizable.strings #1996

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3512
> Update privacy-policy.html #3512

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Homescreen - Wurden sie getestet: The Homescreen section "Wurden sie getestet" shall be adopted to the new design
New: text for the submit card and text for the button.
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3756
> TASK 3756 – New Text For Submit Card & Button

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
EXPOSUREAPP-3887 - added some missing punctuation marks
> Update Localizable.strings [EXPOSUREAPP-3887]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Changes the button title on positive test result cell from "Weiter" to "Andere warnen".
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3760
feat
> Change button title on positive test result cell

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Text changes for EXPOSUREAPP-4030. (Cherry picked)
> Required (legal) text changes for EXPOSUREAPP-4030

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
Corrected grammatical error in legal text
> Update Localizable.legal.strings [EXPOSUREAPP-4150]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html
Added a '.' and a ',' in legal text.
> Update usage.html [EXPOSUREAPP-3079]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Fixed text discrepancies in legal texts
> Update Localizable.strings [EXPOSUREAPP-4204]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Update Localizable.strings [EXPOSUREAPP-4296]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
New sentence on the ThankYou screen:
"Nutzen Sie hierfür Ihr Kontakt-Tagebuch. Sie können die Einträge einfach exportieren und ausdrucken oder als E-Mail verschicken."
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4326
n/a
> Mention the contact journal on ThankYou screen

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Text on the home screen tile 'diary' changed
open journal button text changed
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4612
> updated text on home screen tile

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Adds the localizable strings for the statistics feature so they can go through the translation process.
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3411
> Add localizable strings for statistics

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Just adds the new strings for the end-of-life behaviour story.
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4781
> Add new localizable strings for end-of-life behaviour

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Texts needed for the datadonation list selection screens
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5077
> Datadonation list value strings

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
fixed the data privacy note for DE
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5309?filter=58020
> data privacy note 1.13 DE

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Small addition to the previous PR: https://github.com/corona-warn-app/cwa-app-ios/pull/2031.
> added a dash in the quick action menu

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
This PR contains the localized strings for the new version features 1.15
[JIRA Ticket 5252](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5252)
> Feature/5252 translations adjust info screen to announce new release features for 1.15

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Removed Duplicate Text Strings from Localizable.strings
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4497
n/a
> fix/Removed Duplicate Text Strings from Localizable.strings

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
The text versions deviated slightly between Android and iOS (Android slightly 'politer' -> Bitte denken Sie daran...'
I adapted the iOS text to match the Android version.
> Slight text adjustment to sync with Android text (re: Risikoüberprüfung regelmässig anstoßen [EXPOSUREAPP-5541]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
This PR removes some keys that got duplicated.
> Remove duplicated Keys from strings

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Localizable strings for the QR code generation
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5662
> QR code configuration strings

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
german localized texts for editing checkin times
> localized strings for adjust checkin times

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
This is a wording change for the new version features 2.0 info.
JIRA Ticket https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6229
> Wording changes for new version features 2.0

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Added missing commas and capitalized 'Sie'.
See also EXPOSUREAPP-6204
> https://github.com/corona-warn-app/cwa-app-android/pull/2747#6204

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
Incorrect capitalization of Check-**i**n in data privacy policy
See also EXPOSUREAPP-6461
> Capitalization of 'Check-in' in privacy-policy.html #6461

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Updated text of alert if format of QR Code seems to be wrong, when scanning from iOS camera App
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6586
> updated alert text if qr code format is wrong

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Fixed typo (eingescheckt).
See also community PR https://github.com/corona-warn-app/cwa-app-ios/pull/2500.
> Fix for typo in New Functions

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Fix typo in New Functions UI

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Minor hotline text change to different number and service hours
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6587
> Technical Hotline - wrong phone number and wrong time of availability

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> Fix typo PRC -> PCR [EXPOSUREAPP-6644]

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Added missing hyphen 'PCR-Test'
> Update Localizable.strings - missing hyphen 'PCR-Test'

- src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
Corrected the article -> ein Fehlerprotokoll
> Fixed typo in 'Neue Funktionen' Screen (DE) - Fehlerprotokoll
